// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ringbufferEvent struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ringbufferMapEvents        = "events"
	ringbufferProgKprobeExecve = "kprobe_execve"
)

// loadRingbuffer returns the embedded CollectionSpec for ringbuffer.
func loadRingbuffer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RingbufferBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ringbuffer: %w", err)
	}

	return spec, err
}

// loadRingbufferObjects loads ringbuffer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ringbufferObjects
//	*ringbufferPrograms
//	*ringbufferMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRingbufferObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRingbuffer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ringbufferSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ringbufferSpecs struct {
	ringbufferProgramSpecs
	ringbufferMapSpecs
	ringbufferVariableSpecs
}

// ringbufferProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ringbufferProgramSpecs struct {
	KprobeExecve *ebpf.ProgramSpec `ebpf:"kprobe_execve"`
}

// ringbufferMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ringbufferMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ringbufferVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ringbufferVariableSpecs struct {
}

// ringbufferObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRingbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type ringbufferObjects struct {
	ringbufferPrograms
	ringbufferMaps
	ringbufferVariables
}

func (o *ringbufferObjects) Close() error {
	return _RingbufferClose(
		&o.ringbufferPrograms,
		&o.ringbufferMaps,
	)
}

// ringbufferMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRingbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type ringbufferMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ringbufferMaps) Close() error {
	return _RingbufferClose(
		m.Events,
	)
}

// ringbufferVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRingbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type ringbufferVariables struct {
}

// ringbufferPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRingbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type ringbufferPrograms struct {
	KprobeExecve *ebpf.Program `ebpf:"kprobe_execve"`
}

func (p *ringbufferPrograms) Close() error {
	return _RingbufferClose(
		p.KprobeExecve,
	)
}

func _RingbufferClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ringbuffer_bpfeb.o
var _RingbufferBytes []byte
